<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("INSERT INTO `products` (`id`, `title`, `slug`, `summary`, `description`, `photo`, `stock`, `condition`, `status`, `price`, `size`, `feature`, `created_at`, `updated_at`) VALUES
        (1, 'Paradise Trail Outdoor Swivel Lounge Chair', 'product-1', 'Pretty enough for trendy interiors, yet durable enough to weather the elements, the Paradise Trail outdoor swivel lounge chair rises to the challenge beautifully.', 'Pretty enough for trendy interiors, yet durable enough to weather the elements, the Paradise Trail outdoor swivel lounge chair rises to the challenge beautifully. Handwoven resin wicker over rust-proof aluminum merges high style with low maintenance. Rest assured, though the exposed armrests and swivel base look remarkably like wood, their sturdy aluminum construction is perfectly suited for al fresco living. Plush seat cushions wrapped in high-performing Nuvella® fabric aim to please.\r\nSet of 2\r\nAll-weather, handwoven resin wicker over rust-proof aluminum frame\r\nAluminum armrests and base with wood-like finish\r\nSeat cushions covered with high-performance Nuvella® fabric\r\nClean fabric with mild soap and water, let air dry; for stubborn stains, use a solution of 1 cup bleach to 1 gallon water\r\nAll-weather foam cushion core wrapped in soft polyester\r\n360-degree swivel\r\nShips in single box\r\nImported fabric and fill\r\nAssembly required\r\nEstimated Assembly Time: 30 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/P750-821-FRONT-SW?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 1187, 'Width: 32.75\"\r\nDepth: 33.50\"\r\nHeight: 38.75\"', '', NULL, NULL),
        (2, 'Tartonelle Accent Chair', 'product-2', 'Fresh and sophisticated. The Tartonelle accent chair with button tufting is a classy addition to your home. Inside-out design with linen weave fabric on the seating area and taupe faux leather on the back', 'Fresh and sophisticated. The Tartonelle accent chair with button tufting is a classy addition to your home. Inside-out design with linen weave fabric on the seating area and taupe faux leather on the back. Large nailhead trim ties the look together. Charles of London arms and turned bun feet make this a stylish heirloom piece.\r\nAttached back and loose seat cushions\r\nHigh-resiliency foam cushions wrapped in thick poly fiber\r\nLinen weave interior upholstery; faux leather exterior upholstery\r\nPolyester upholstery\r\nExposed feet with faux wood finish\r\nEstimated Assembly Time: 15 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/A3000053-SW-KO?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 279, 'Width: 31.50\" Depth: 35.50\" Height: 37.25\"', '', NULL, NULL),
        (3, 'Klorey Chair', 'product-3', 'With its angular legs, button tufting and tailored flair, Klorey accent chair is clearly inspired by the best in mid-century design.', 'With its angular legs, button tufting and tailored flair, Klorey accent chair is clearly inspired by the best in mid-century design. The barrel style is as cool and relevant now as it was then. Textural weave of the upholstery so enriches the neutral hue.\r\nHigh-resiliency foam cushions wrapped in thick poly fiber\r\nPolyester upholstery\r\nExposed legs with faux wood finish\r\nCorner-blocked frame\r\nTufted back cushion with loose seat cushion\r\nExcluded from promotional discounts and coupons\r\nEstimated Assembly Time: 15 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/36208-21-HEAD-ON-SW-QL?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 206, 'Width: 30.75\" Depth: 30.50\" Height: 31.50\"', '', NULL, NULL),
        (4, 'Clarinda Accent Chair', 'product-4', 'Clarinda is one part classic slipper chair, one part traditional wingback chair and 100 percent modern. Tapered legs', 'Clarinda is one part classic slipper chair, one part traditional wingback chair and 100 percent modern. Tapered legs, clean lines and subtle tufting add fashionable flair, while the deep seat and winged back offer cozy comfort.\r\nCorner-blocked frame\r\nAttached back and seat cushions\r\nHigh-resiliency foam cushions wrapped in thick poly fiber\r\nPolyester upholstery\r\nExposed feet with faux wood finish\r\nExcluded from promotional discounts and coupons\r\nEstimated Assembly Time: 30 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/36230-60-SW-P1-KO?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 203, 'Width: 27.00\" Depth: 31.75\" Height: 33.75\"', '', NULL, NULL),
        (5, 'Dericka Accent Chair', 'product-5', 'Amp up the cool factor in your room with the Dericka accent chair as you sit back and relax in contemporary comfort. A steel gray polyester velvet provides a sumptuous perch from which to soak up the very modern space you’ve created.', 'Amp up the cool factor in your room with the Dericka accent chair as you sit back and relax in contemporary comfort. A steel gray polyester velvet provides a sumptuous perch from which to soak up the very modern space you’ve created.\r\nMade of polyester and metal\r\nSteel gray polyester velvet upholstery\r\nAttached back and seat cushions\r\nMetal legs in black finish\r\nAssembly required\r\nEstimated Assembly Time: 15 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/A3000236-HEAD-ON-SW-P1-KO?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 253, 'Width: 28.25\" Depth: 32.00\" Height: 33.00\"', '', NULL, NULL),
        (6, 'Jarreau Chair', 'product-6', 'Top-of-the-line design and comfort are one and the same with the Jarreau chair. The sleek silhouette and oversized pillow back make it a blissful contemporary retreat that you’ll want to sink back into every time', 'Top-of-the-line design and comfort are one and the same with the Jarreau chair. The sleek silhouette and oversized pillow back make it a blissful contemporary retreat that you’ll want to sink back into every time. The piping along the arms as well as the tapered, exposed feet add a chic, timeless touch to the piece. Perfect for small space living and entertaining.\r\nCorner-blocked frame\r\nLoose cushions\r\nHigh-resiliency foam cushions wrapped in thick poly fiber\r\nPolyester upholstery\r\nExposed feet with faux wood finish\r\nEstimated Assembly Time: 15 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/11502-20-SW-P1-KO?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 259, 'Width: 35.50\" Depth: 34.00\" Height: 35.00\"', '', NULL, NULL),
        (10, 'Alenya Chair', 'alenya-chair', 'Celebrate your worldly good taste and flair for très chic twists with the Alenya accent chair. With its plush comfort and fanciful French scripting, it speaks the language of casually cool style.', 'Celebrate your worldly good taste and flair for très chic twists with the Alenya accent chair. With its plush comfort and fanciful French scripting, it speaks the language of casually cool style.\r\nCorner-blocked frame\r\nAttached back and loose seat cushion\r\nHigh-resiliency foam cushion wrapped in thick poly fiber\r\nLinen/viscose upholstery\r\nExposed legs with faux wood finish\r\nExcluded from promotional discounts and coupons\r\nEstimated Assembly Time: 15 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/16600-21-P1-KO?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 399, 'Width: 34.63\" Depth: 36.75\" Height: 35.63\"', '', NULL, NULL),
        (11, 'Peacemaker Accent Chair', 'peacemaker-accent-chair', 'Find the perfect balance of high style and plush comfort with the Peacemaker accent chair. Ultra-linear metal frame and box seat cushion styling are sure to appeal to contemporary tastes.', 'Find the perfect balance of high style and plush comfort with the Peacemaker accent chair. Ultra-linear metal frame and box seat cushion styling are sure to appeal to contemporary tastes. Weathered faux leather in a light brown tone give this cool chair a sense of warmth.\r\nExposed metal frame in antique brass finish\r\nFaux leather upholstery\r\nUpholstery-wrapped padded armrests\r\nEstimated Assembly Time: 30 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/A3000029-SW-P1-KO?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 315, 'Width: 27.75\" Depth: 31.25\" Height: 36.00\"', '', NULL, NULL),
        (12, 'Engineer Accent Chair', 'engineer-accent-chair', 'The modestly scaled Engineer accent chair is a chic design feat. Perfect for a corner spot or entryway, this curvaceous beauty sports a distressed finished frame and taupe-tone upholstery for an easy-on-the-eyes sensibility.', 'The modestly scaled Engineer accent chair is a chic design feat. Perfect for a corner spot or entryway, this curvaceous beauty sports a distressed finished frame and taupe-tone upholstery for an easy-on-the-eyes sensibility. Nailhead trim punctuating the front and back adds so much cool attitude.\r\nAttached back and seat cushions\r\nNailhead trim\r\nExposed frame in faux wood finish\r\nExcluded from promotional discounts and coupons\r\nEstimated Assembly Time: 15 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/A3000030-HEAD-ON-SW-QL?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 333, 'Width: 28.25\" Depth: 26.50\" Height: 34.00\"', '', NULL, NULL),
        (13, 'Tibbee Accent Chair', 'tibbee-accent-chair', 'Tibbee slipper chair slips clean, contemporary flair into a simply striking profile. Whether accompanying other Tibbee pieces in a living room, or bringing space-conscious seating to an office or bedroom, what a fresh style awakening.', 'Tibbee slipper chair slips clean, contemporary flair into a simply striking profile. Whether accompanying other Tibbee pieces in a living room, or bringing space-conscious seating to an office or bedroom, what a fresh style awakening.\r\nCorner-blocked frame\r\nAttached back and seat cushions\r\nHigh-resiliency foam cushions wrapped in thick poly fiber\r\nPolyester upholstery\r\nExposed legs with faux wood finish\r\nExcluded from promotional discounts and coupons\r\nEstimated Assembly Time: 30 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/99101-60-SW-P1-KO?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 181, 'Width: 21.50\" Depth: 30.50\" Height: 31.00\"', '', NULL, NULL),
        (14, 'Alarick Accent Chair', 'alarick-accent-chair', 'A wire brushed frame in brown finish, a slight pitched back and two-tone cream upholstery is the Alarick accent chair. Perfect on its own or pair it up.', 'A wire brushed frame in brown finish, a slight pitched back and two-tone cream upholstery is the Alarick accent chair. Perfect on its own or pair it up.\r\nWood and polyester\r\nAttached back and seat cushion\r\nWood frame\r\nEasy assembly\r\nEstimated Assembly Time: 30 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/A3000259-SW-P1-KO?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 297, 'Width: 29.00\" Depth: 30.50\" Height: 34.25\"', '', NULL, NULL),
        (15, 'Fayme Accent Chair', 'fayme-accent-chair', 'On-trend and exceedingly stylish, the Fayme mid-century modern lounge chair is sure to be hit with your contemporary home.', 'On-trend and exceedingly stylish, the Fayme mid-century modern lounge chair is sure to be hit with your contemporary home. Featuring a solid wood armless frame in dark brown finish with leather strip woven back and seat in camel-tone basket weave pattern.\r\nWood and leather\r\nWood frame with dark brown finish\r\nIndoor use only\r\nEasy assembly\r\nEstimated Assembly Time: 15 Minutes', 'https://ashleyfurniture.scene7.com/is/image/AshleyFurniture/A3000282-SW-P1-KO?$AFHS-PDP-Zoomed$', 10, 'new', 'active', 213, 'Width: 24.38\" Depth: 34.50\" Height: 32.88\"', '', NULL, NULL);
        ");
    }
}
